Chapter 5
shiffman/The-Nature-of-Code-Examples-Python pull request #4
Opened 2017-02-18 16:26 UTC by hirtiganto

Port of some chapter 5 examples

2017-02-18 17:16 UTC, jdf requested changes
Thanks for doing this work. I'm hope these comments will help.

2017-02-18 17:16 UTC, jdf commented on chp05_physicslibraries/CollisionEqualMass/CollisionEqualMass.pyde
> +b = None
This is a matter of taste, but because these lines don't do anything, I'd be happier without them. My reasoning is that it might create a cargo-cult belief that you need to "declare" global variables.

2017-02-18 17:16 UTC, jdf commented on chp05_physicslibraries/CollisionEqualMass/CollisionEqualMass.pyde
> +showVectors = True
Whereas this line actually does something meaningful, since that starting value is useful in `draw()`.

2017-02-18 17:16 UTC, jdf commented on chp05_physicslibraries/CollisionEqualMass/Mover.py
> +
Do you really mean for these to be class variables? It looks to me like `vel` and `loc`, at least, are actually instance variables, which makes these lines meaningless or incorrect.

2017-02-18 17:16 UTC, jdf commented on chp05_physicslibraries/CollisionEqualMass/Mover.py
> +    directionVector.normalize()
It's nice to see comments; you might consider doing them using the [PEP 257](https://www.python.org/dev/peps/pep-0257/) docstring conventions.

2017-02-18 17:16 UTC, jdf commented on chp05_physicslibraries/NOC_5_1_box2d_exercise/Box.py
> +
Same comment here. These don't mean what I think you mean them to mean.

2017-02-20 16:36 UTC, hirtiganto commented
Thanks for feedback! I fixed all the issues you mentioned

2017-02-20 16:40 UTC, jdf requested changes

2017-02-20 16:40 UTC, jdf commented on chp05_physicslibraries/CollisionEqualMass/CollisionEqualMass.pyde
> +    global a, b, showVectors
This global statement is not needed, because you are not assigning to those names.

2017-02-20 16:40 UTC, jdf commented on chp05_physicslibraries/CollisionEqualMass/Mover.py
> +    def collideEqualMass(self, other):
This file (and maybe others) needs to be auto-formatted by the Python Mode editor or any other PEP-8 formatter.

2017-02-20 16:40 UTC, jdf commented on chp05_physicslibraries/NOC_5_1_box2d_exercise/NOC_5_1_box2d_exercise.pyde
> +    global boxes
This statement is not needed, because you are not assigning to that name.

2017-02-20 16:57 UTC, hirtiganto commented
I hope everything's alright this time

2017-02-21 15:05 UTC, jdf commented on chp05_physicslibraries/CollisionEqualMass/Mover.py
> +    pushMatrix()
Missing a popMatrix()?

2017-02-22 17:32 UTC, hirtiganto commented on chp05_physicslibraries/CollisionEqualMass/Mover.py
> +    pushMatrix()
Fixed.

2017-02-24 16:48 UTC, hirtiganto commented
Fixed

2017-02-24 17:30 UTC, jdf approved these changes

2017-02-25 04:09 UTC, shiffman commented
Hooray! Thank you @hirtiganto for this wonderful work and @jdf for reviewing!

2017-02-25 04:09 UTC, merged